//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThucUong_NguyenLieu
    {
        public string MaThucUong { get; set; }
        public string MaNguyenLieu { get; set; }
        public Nullable<int> LuongDung { get; set; }
        public string DonViTinh { get; set; }
    
        public virtual NguyenLieu NguyenLieu { get; set; }
        public virtual ThucUong ThucUong { get; set; }
    }
}
